"""The version is single-sourced from the git tag, and stays that way.

`hatch-vcs` derives the distribution version from `git describe`, writes it into the
generated `src/gliquid/_version.py` at build time, and `gliquid.__init__` reads it back
only when no installed distribution supplies metadata. Nothing here asserts a *specific*
number: under `hatch-vcs` the answer depends on the git state of whoever is running, so a
hardcoded expectation would fail on every developer machine and in every CI checkout.

What is worth pinning is the shape of the wiring, because both ways it breaks are silent —
they produce a wrong version rather than an error:

* a version literal creeps back into `src/gliquid/`, and the package reports a stale number
  forever after;
* the `pyproject.toml` wiring regresses to a static `version =` key, or loses the
  `fallback-version` that gives a tree with no reachable tag -- an archived branch, a
  shallow CI checkout, a build run outside a clone -- a defined answer.
"""

import ast
import re
from importlib import metadata
from pathlib import Path

import pytest
from packaging.version import Version

import gliquid

# A string shaped like a release number: 1.2, 1.2.3, 2026.06.16, 0.1.0rc0, 1.2.3+local.
# Deliberately anchored and narrow so it fires on versions and not on tolerances, ratios,
# or the dotted numbers that appear throughout the thermodynamic code.
_VERSION_LIKE = re.compile(
    r"^\d{1,4}\.\d{1,3}(\.\d{1,4})?([-_.]?(a|b|c|rc|alpha|beta|pre|post|dev)\d*)?"
    r"(\+[A-Za-z0-9.]+)?$"
)

# The single permitted exception: the sentinel __init__ reports from a source tree with
# neither an install nor a build. It claims no version, which is exactly the point.
_UNKNOWN_SENTINEL = "0.0.0+unknown"


def _repo_root() -> Path | None:
    """The checkout this test file lives in, or None when it does not ship with one.

    Identified by structure -- the directory holding both ``pyproject.toml`` and
    ``src/gliquid`` -- rather than by a parent index or a repo name, so neither moving this
    file between test tiers nor cloning the repo under another name misdirects the scan.
    """
    for parent in Path(__file__).resolve().parents:
        if (parent / "pyproject.toml").is_file() and (parent / "src" / "gliquid").is_dir():
            return parent
    return None


def _version_literals(root: Path) -> list[str]:
    """Every version-shaped string constant under ``root``, as ``path:lineno: value``."""
    found = []
    for path in sorted(root.rglob("*.py")):
        if path.name == "_version.py":  # generated by hatch-vcs; gitignored, never authored
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if not (isinstance(node, ast.Constant) and isinstance(node.value, str)):
                continue
            text = node.value.strip()
            if text != _UNKNOWN_SENTINEL and _VERSION_LIKE.match(text):
                found.append(f"{path}:{node.lineno}: {text!r}")
    return found


def _table(pyproject: Path, name: str) -> list[str]:
    """The stripped lines of one TOML table, up to the next table header.

    Text, not `tomllib`: this suite still runs on 3.10, where `tomllib` does not exist.
    Only a header at column 0 closes the table, so a table name mentioned inside a comment
    does not truncate it.
    """
    lines = pyproject.read_text(encoding="utf-8").splitlines()
    start = lines.index(f"[{name}]") + 1
    body = []
    for line in lines[start:]:
        if line.startswith("["):
            break
        body.append(line.strip())
    return body


class TestReportedVersion:
    def test_is_a_pep440_version(self):
        Version(gliquid.__version__)  # raises InvalidVersion if it is not

    def test_matches_the_installed_distribution(self):
        try:
            installed = metadata.version("gliquid")
        except metadata.PackageNotFoundError:
            pytest.skip("gliquid is not installed; __version__ comes from _version.py")
        assert gliquid.__version__ == installed


class TestNoVersionLiteralInSource:
    """The regression this whole spec exists to prevent."""

    def test_package_source_holds_no_version_literal(self):
        root = _repo_root()
        if root is None:
            pytest.skip("not running from a source checkout")
        offenders = _version_literals(root / "src" / "gliquid")
        assert not offenders, "hardcoded version literal in src/gliquid: " + "; ".join(offenders)

    def test_scan_catches_a_reintroduced_literal(self, tmp_path):
        """Control: the scan above is only meaningful if it can still fail."""
        (tmp_path / "regression.py").write_text('__version__ = "2026.06.16"\n', encoding="utf-8")
        assert _version_literals(tmp_path)

    def test_scan_allows_the_unknown_sentinel(self, tmp_path):
        planted = f'__version__ = "{_UNKNOWN_SENTINEL}"\n'
        (tmp_path / "sentinel.py").write_text(planted, encoding="utf-8")
        assert _version_literals(tmp_path) == []


class TestPyprojectWiring:
    @pytest.fixture
    def pyproject(self):
        root = _repo_root()
        if root is None:
            pytest.skip("not running from a source checkout")
        return root / "pyproject.toml"

    def test_version_is_dynamic_and_not_static(self, pyproject):
        body = _table(pyproject, "project")
        assert any(re.fullmatch(r'dynamic\s*=\s*\[\s*"version"\s*\]', line) for line in body)
        assert not any(re.match(r"version\s*=", line) for line in body)

    def test_build_backend_requires_hatch_vcs(self, pyproject):
        build_system = _table(pyproject, "build-system")
        assert any("hatch-vcs" in line for line in build_system)

    def test_vcs_source_declares_a_fallback(self, pyproject):
        """Without a fallback, a build with no SCM data at all errors out."""
        version_table = _table(pyproject, "tool.hatch.version")
        assert any(re.fullmatch(r'source\s*=\s*"vcs"', line) for line in version_table)
        assert any(re.fullmatch(r'fallback-version\s*=\s*"[^"]+"', line) for line in version_table)
